---
- hosts: all
  become: true
  tasks:

    - name: update Ubuntu
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: upgrade CentOS
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
